/**
 * AI Reading panel for Human Design
 *
 * Displays full AI-generated reading with sections
 */
import React from 'react'
import { useHDStore } from '../stores/hdStore'
import { Button } from '@/components/ui/Button'

interface AIReadingProps {
  className?: string
  birthDataId: string
}

export const AIReading: React.FC<AIReadingProps> = ({ className = '', birthDataId }) => {
  const { reading, isLoadingReading, error, generateReading } = useHDStore()

  if (!reading && !isLoadingReading) {
    return (
      <div className={`flex flex-col items-center justify-center p-8 ${className}`}>
        <div className="text-center mb-6">
          <h3 className="text-lg font-medium text-white mb-2">AI-Generated Reading</h3>
          <p className="text-sm text-gray-400 max-w-md">
            Get a comprehensive, personalized interpretation of your Human Design chart
            generated by AI analysis of your unique configuration.
          </p>
        </div>
        <Button
          onClick={() => generateReading(birthDataId)}
          className="bg-celestial-gold text-gray-900 hover:bg-celestial-gold/90"
        >
          Generate Full Reading
        </Button>
        {error && <p className="text-red-400 text-sm mt-4">{error}</p>}
      </div>
    )
  }

  if (isLoadingReading) {
    return (
      <div className={`flex flex-col items-center justify-center p-8 ${className}`}>
        <div className="animate-spin w-8 h-8 border-2 border-celestial-gold border-t-transparent rounded-full mb-4" />
        <p className="text-gray-400">Generating your personalized reading...</p>
        <p className="text-xs text-gray-500 mt-2">This may take a moment</p>
      </div>
    )
  }

  if (!reading) return null

  const sections = [
    { title: 'Type & Strategy', content: reading.sections.type_strategy },
    { title: 'Authority', content: reading.sections.authority },
    { title: 'Profile', content: reading.sections.profile },
    { title: 'Definition', content: reading.sections.definition },
    { title: 'Channels', content: reading.sections.channels },
    { title: 'Incarnation Cross', content: reading.sections.incarnation_cross },
    { title: 'Centers', content: reading.sections.centers },
    ...(reading.sections.variables ? [{ title: 'Variables (PHS)', content: reading.sections.variables }] : []),
  ]

  return (
    <div className={`space-y-6 ${className}`}>
      {/* Full Reading */}
      <div className="prose prose-invert max-w-none">
        <div className="bg-gray-800/50 rounded-lg p-4 mb-6">
          <p className="text-gray-300 whitespace-pre-wrap leading-relaxed">{reading.reading}</p>
        </div>
      </div>

      {/* Sectioned Reading */}
      <div className="space-y-4">
        <h3 className="text-lg font-medium text-celestial-gold">Detailed Sections</h3>
        {sections.map((section, index) => (
          <details
            key={section.title}
            className="group bg-gray-800/30 rounded-lg"
            open={index === 0}
          >
            <summary className="cursor-pointer px-4 py-3 flex items-center justify-between text-white font-medium hover:bg-gray-800/50 rounded-lg transition-colors">
              {section.title}
              <span className="text-gray-500 group-open:rotate-180 transition-transform">
                ▼
              </span>
            </summary>
            <div className="px-4 pb-4 pt-2 text-sm text-gray-300 whitespace-pre-wrap leading-relaxed">
              {section.content}
            </div>
          </details>
        ))}
      </div>

      {/* Regenerate Button */}
      <div className="flex justify-center pt-4 border-t border-gray-700">
        <Button
          onClick={() => generateReading(birthDataId)}
          variant="outline"
          className="border-gray-600 text-gray-400 hover:text-white"
        >
          Regenerate Reading
        </Button>
      </div>
    </div>
  )
}

export default AIReading
