"""Add chart_interpretations table for AI-generated descriptions

Revision ID: 93d218e8012f
Revises: 
Create Date: 2025-11-15 15:24:01.994747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93d218e8012f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite uses String for UUIDs and timestamps (ISO 8601 format)
    op.create_table(
        "chart_interpretations",
        sa.Column("chart_id", sa.String(), nullable=False),
        sa.Column("element_type", sa.String(length=50), nullable=False),
        sa.Column("element_key", sa.String(length=255), nullable=False),
        sa.Column("ai_description", sa.Text(), nullable=False),
        sa.Column("ai_model", sa.String(length=100), nullable=True),
        sa.Column("ai_prompt_version", sa.String(length=50), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_approved", sa.String(length=20), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["chart_id"], ["charts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_chart_interp_lookup",
        "chart_interpretations",
        ["chart_id", "element_type", "element_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chart_interpretations_chart_id"),
        "chart_interpretations",
        ["chart_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chart_interpretations_created_at"),
        "chart_interpretations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chart_interpretations_element_type"),
        "chart_interpretations",
        ["element_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chart_interpretations_id"), "chart_interpretations", ["id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chart_interpretations_id"), table_name="chart_interpretations")
    op.drop_index(op.f("ix_chart_interpretations_element_type"), table_name="chart_interpretations")
    op.drop_index(op.f("ix_chart_interpretations_created_at"), table_name="chart_interpretations")
    op.drop_index(op.f("ix_chart_interpretations_chart_id"), table_name="chart_interpretations")
    op.drop_index("ix_chart_interp_lookup", table_name="chart_interpretations")
    op.drop_table("chart_interpretations")
    # ### end Alembic commands ###
